#!/bin/sh

xrdb -merge $XDG_CONFIG_HOME/X11/Xresources

# Source external programs installed for xinit
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Set the keyboard layout
setxkbmap -layout us -variant dvp -option ctrl:nocaps

# Set touchpad settings
touchpad_id=$(xinput list | grep touchpad -i | sed 's/.*id=([0-9]+).*/\1/' -E)

xinput set-prop $touchpad_id "libinput Tapping Enabled" 1
xinput set-prop $touchpad_id "libinput Tapping Button Mapping Enabled" 1 0
xinput set-prop $touchpad_id "libinput Disable While Typing Enabled" 1
xinput set-prop $touchpad_id "libinput Horizontal Scroll Enabled" 1
xinput set-prop $touchpad_id "libinput Natural Scrolling Enabled" 1

# Turn numlock on
numlockx &

exec bspwm
