#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Set the keyboard layout
setxkbmap -layout us -variant dvp -option ctrl:nocaps

# Set touchpad settings
touchpad_id=$(xinput list | grep touchpad -i | sed 's/.*id=([0-9]+).*/\1/' -E)

xinput set-prop $touchpad_id "libinput Tapping Enabled" 1
xinput set-prop $touchpad_id "libinput Tapping Button Mapping Enabled" 1 0
xinput set-prop $touchpad_id "libinput Disable While Typing Enabled" 1
xinput set-prop $touchpad_id "libinput Horizontal Scroll Enabled" 1
xinput set-prop $touchpad_id "libinput Natural Scrolling Enabled" 1

exec bspwm
