#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Set initial background randomly.
feh --bg-fill --no-fehbg --randomize "$(xdg-user-dir PICTURES)"/wallpapers/*

# Start the compositor.
picom &

# ensure backlight never goes completely dark
light -N 10

# playerctl should control the most recently played media
playerctld daemon

polybar_battery="$(estragon envvar --dir ~/dotfiles polybar_battery)" \
    polybar_adapter="$(estragon envvar --dir ~/dotfiles polybar_adapter)" \
    polybar &

nm-applet &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop="^10"
bspc rule -a discord desktop="^9"
bspc rule -a spotify desktop="^8"
bspc rule -a obsidian desktop="^7"

kitty &
firefox &
discord &
spotify-launcher &
obsidian &

bspc config external_rules_command "$XDG_CONFIG_HOME/bspwm/scripts/spotify.sh"
