require "core/options"
require "core/map"
require "core/colorscheme"
require "core/indent"
require "core/ftdetect"

require "plugins"
require "plugins/lualine"
require "plugins/nvim-tree"
require "plugins/nvim-cmp"
require "plugins/mason"
require "plugins/lsp"
require "plugins/null-ls"
require "plugins/gitsigns"
